### ISSUE TITLE
Add Black background on Globe

### ISSUE THREAD

**Issue by gbrunner** [gbrunner/Map-of-the-Sky#4]
@jwasilgeo Can we put a black background over the globe, kind of like Heather Smith has in her star chart?
- http://www.arcgis.com/home/webmap/viewer.html?webmap=7e8032ace3f94a4aac161522bee7996d

**Comment by jwasilgeo** [comment]
@ycabon what we have here is a `Map` with only a single `TileLayer` added to a `SceneView`.

Will there be any upcoming JSAPI functionality to alter the base globe in a `SceneView` without doing something wild with external renderer code?

Otherwise, is our option right now to create a solid black vector tile layer and add it to the `Map`?

**Comment by ycabon** [comment]
Currently the trick for this is a custom tile layer, that returns a black canvas 256x256 + no atmostphere.
https://codepen.io/ycabon/pen/gvXqqj?editors=1000#

**Comment by jwasilgeo** [comment]
That is a really cool idea!  Thank you!
